### ISSUE TITLE
Syntax error on IE11

### ISSUE THREAD

**Issue by bjoe2k4** [jhabdas/fetch-inject#15]
IE11 dies on syntax error in fetch-inject.min.js i.e. on https://codepen.io/jhabdas/pen/MpVeOE?editors=0012 no matter if the code is excluded via `if (window.fetch) ...`

**Comment by bjoe2k4** [comment]
Okay, have to use ES6=>ES5 transpiler. Maybe it would be better to host an ES5 version of this lib via CDN.

**Comment by jhabdas** [comment]
Just noticed I forgot to add a note here: https://github.com/jhabdas/fetch-inject#supported-browsers defines browsers with support for Fetch Injection. And I've added instructions for Progressive Enhancement to the README as well.
