### ISSUE TITLE
Support Fetching of Web Fonts

### ISSUE THREAD

**Issue by monolux** [jhabdas/fetch-inject#16]
Would you know if loading FontFaceObserverwith with fetch-inject instead of inline as seen in this example `view-source:https://www.zachleat.com/web-fonts/demos/critical-foft-preload.html` prove useful [*](https://www.zachleat.com/web/comprehensive-webfonts/#critical-foft-preload), or does fetch-inject perhaps have a use case for any type of optimized web font loading?

**Comment by jhabdas** [comment]
I'll have to look later at the example but want to provide what I know now.

I've tested inlining WebFonts using base64 encoding and while inlining fonts increases Page Speed scores it also reduces perceptible performance as a result of Page weight, unless applied like Critical CSS (e.g. only loading the needed glyphs for above the fold content and lazyloading the rest). I have metrics to back this statement up.

As it stands CSS-based Web Fonts such as Font Awesome can be loaded using Fetch Inject. And while it may lead to a momentary FOUC faster loading times and faster connection speeds minimize the delay resulting is a faster first paint metric despite what the browser thinks is best for UX. This technique may also be applied to dynamically loading WOFF2 files with fetch for accelerated load times, and can work in conjunction with Server Push under HTTP/2 for fonts pushed to clients on initial request.

Regarding preloading and FFO, I need to do more research in that area before I can provide advice there.

For more info on Server Push and use with Fetch please see comments here: https://www.smashingmagazine.com/2017/04/guide-http2-server-push/

**Comment by monolux** [comment]
Thank you indeed for sharing your research! Always happy to dig into metrics, thank you if you can show the test case. How did  you extract the characters needed for the above the fold content from the type, is that possible with Google web fonts?

Did not know one can load WOFF2 with Fetch Inject, that's great actually. I can forget about trying it with WOFF files, right? Support for WOFF2 is good. So have Fetch Inject load both, the WOFF2 file and the normal CSS with the @font-face rule once the font is done? Will try that and also look at Server Push for fonts for sure, thx!

The preloading example also uses a two version font approach similar to what you tested and mentioned first. Very interesting and I find quite important, text being the first impression a user has in possibly quite a few cases, expect something like [this](http://audiograph.xyz/). So making that first impression just nice for people looking to read something in a smooth way, that is really something cool.

Weather a short FOUC or an avoided FOIT with a larger size document on the other hand is better is surly also personal perception, I'd rather have text fast/immediately that slightly changes rather than no text.

**Comment by jhabdas** [comment]
Need to dig up the specific test. Data is on http://speed.habd.as under WordCamp (Cable) profile and Font inlining test should be dated at or near 4/20. The number of fonts loading should hit zero for that test. Data available in graphs.

> How did you extract the characters needed for the above the fold content from the type, is that possible with Google web fonts?

I haven't done this yet. But I've read about the idea and it seems doable depending on the font used. Here's how to inline them, and linked tutorial within may have been the source of the critical font idea: https://habd.as/turbocharge-your-octopress-blog/#inline-web-fonts

> Did not know one can load WOFF2 with Fetch Inject, that's great actually. I can forget about trying it with WOFF files, right?

Yeah. Probably forget about WOFF as long as there's a suitable fallback right? Fetch Inject may need to be updated to support the font resource MIME type to be loaded. But will need to see a common use case emerge. Right now CSS can import font and if CSS is fetched it won't block and webfonts get downloaded from the CSS.

Def more work to be done here if you'd like to spearhead. I need to work on the Hyperdrive for the next two weeks or so to prep it for 1.0.0.

Thanks for this good info dump, super valuable.

**Comment by jhabdas** [comment]
@monolux here's an example where only providing the glyphs necessary would have a big bang for the byte: https://hackcabin.com/404.html

**Comment by jhabdas** [comment]
Closing this for now until a use case becomes clearer. Please feel free to continue discussion in closed thread. Need to spend cycles elsewhere right now.
