### ISSUE TITLE
CSS injected inside <script> tags in Firefox

### ISSUE THREAD

**Issue by jhabdas** [jhabdas/fetch-inject#20]
Filed browser bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1362824. And here's a reduced test case: https://bl.ocks.org/jhabdas/87f8bc3573cf91b4c35e0c799addd762

**Comment by bjoe2k4** [comment]
It would be good to update the compatibility section in readme to reflect the current limitations due to unresolved browser bugs. This saves time for developers who are interested in using this lib. Thanks.

**Comment by jhabdas** [comment]
This will soon become a confirmed bug in Firefox.

**Comment by bjoe2k4** [comment]
How are you supposed to detect this bug at the moment in production?

**Comment by jhabdas** [comment]
> How are you supposed to detect this bug at the moment in production?

[Read the docs](https://github.com/jhabdas/fetch-inject/blob/master/README.md#supported-browsers).

**Comment by jhabdas** [comment]
Current browser behavior and results of `type` attribute using the reduced test case are documented here at a high level for the sake of simplicity:

- Chrome: `text/css`
- Safari: `text/css`
- Firefox: `text/css; charset=utf-8`
- Opera: `text/css`
- Yandex: `text/css`
- Edge: `text/css; charset=utf-8`

For more details on what constitutes a media "type" please reference:

RFC 2045 - Multipurpose Internet Mail Extensions (MIME)
https://tools.ietf.org/html/rfc2045#section-5.1

> type := discrete-type / composite-type

**Comment by jhabdas** [comment]
Mozilla developers were kind enough to open [an issue](https://github.com/whatwg/fetch/issues/540) against the `fetch` to better understand the expected interpretation of the specification WRT use of `type` attribute as applied to Blob and some other use cases. Please consider giving your emoji for the OP to help expedite the resolution of this issue.
