### ISSUE TITLE
Automate Code Coverage Reporting

### ISSUE THREAD

**Issue by jhabdas** [jhabdas/fetch-inject#22]
Prior to adding unit tests for #4 we need to automate code coverage reporting. We will use Code Climate as an integrated solution and integrate with CI.

https://github.com/codeclimate/javascript-test-reporter

**Comment by jhabdas** [comment]
@bjoe2k4 any interest in spiking on this in your fork?

**Comment by bjoe2k4** [comment]
Sorry, I am at the moment pretty swamped with other work and I have no experience with imprementing code coverage tests, Unit/E2E tests, etc...

For Code coverage it might be useful to un-minify injectors.js in case you want to cover that too.

My fork focuses on compatibility.

**Comment by jhabdas** [comment]
Thanks for your response. It's nice to have a fork to focus on smoothing out browser inconsistencies while spec settles. I understand your busy, but if your time frees up and this becomes of interest here's an example implementation I created earlier this week in another language: https://github.com/comfusion/hyperdrive/pull/33

**Comment by jhabdas** [comment]
Yeah, we definitely won't be going with Code Climate.
