### ISSUE TITLE
isomorphic solution?

### ISSUE THREAD

**Issue by gingur** [jhabdas/fetch-inject#25]
any plans or suggestions on how to support such a syntax on both client and server?

**Comment by jhabdas** [comment]
Hi @gingur. Fetch Inject is intended primarily as a browser library, but it would be adapted for isomorphic apps. I left a small pointer in the [see also section](https://github.com/jhabdas/fetch-inject#see-also) of the README.

> [isomorphic-fetch](https://github.com/matthew-andrews/isomorphic-fetch) - A library for using fetch in Node

I haven't used the above library, but based on my initial research it seemed to a reasonable place to start given Node [does not support](https://github.com/nodejs/node-eps/issues/53) `fetch`.

From there you'd need to handle the globals based on your environment and toolset. And then it should work.

**Comment by gingur** [comment]
Yeah, I saw your readme references to iso tooling so was just curious if it was something in the todo list down the road.  Thanks for the info!

**Comment by jhabdas** [comment]
No problem. I hope someone creates an isomorphic wrapper. That'd be awesome to play around with. Right now I'm busy building the Hyperdrive on top of this sucker. And just hit beta 5 if you're curious to take a peek: https://github.com/comfusion/hyperdrive/blob/master/CHANGELOG.md#100-beta5-2017-05-31
