### ISSUE TITLE
Worse results without FetchInject than with it

### ISSUE THREAD

**Issue by maszynka** [jhabdas/fetch-inject#28]
I'm quiet surprised to see a bit worse results when using Fetch Inject to a typical requests (some of them are async). I took me around 5 hours to make right order and optimize it but results are not satisfying.

![2017-07-22-011525_2416x1680_scrot png 2416x1680](https://user-images.githubusercontent.com/2837542/28485982-f7e1471e-6e7d-11e7-993f-33da80663bb2.png)

The worst part is rendering without cache (first user visit):

![2017-07-22-013557_2416x1680_scrot png 2416x1680](https://user-images.githubusercontent.com/2837542/28486069-b150602c-6e7e-11e7-8374-8c7af1c507de.png)

It takes 700ms longer to render page.

I will share more information if needed.

**Comment by jhabdas** [comment]
@maszynka Thanks for spending time to use asynchronous loading. As much as I would like to provide individual support I cannot do so in every case. If you believe you've found a bug or are requesting an enhancement could you please let us know which of the use cases provided in the README best fits your scenario, if any?

**Comment by jhabdas** [comment]
It's hard to tell exactly what's going on without a HAR, but your images appear to show blocking by images or fonts. If you could share what it is you're hoping to achieve I may be able to provide some guidance. Been building Web for 22 years so I know what 5 hours feels like on a new tool.

**Comment by jhabdas** [comment]
Though I don't see the types for the requests in the images provided it's clear there is some blocking going on here. I'm closing this as we should expect requests blocked in the waterfall to take longer than those which are loaded asynchronously or in parallel.

If you continue to struggle this would be a good issue for StackOverflow or the like, as it is related more closely to how Ajax works in browsers than it is specific to Fetch Inject.

If you do open an SO question please link it here and I'll jump in to try and help answer it for you. Cheers and thanks for stepping into the world of AJAX.
