### ISSUE TITLE
Optional fetch options argument in fetchInject

### ISSUE THREAD

**Issue by TheT0dd** [jhabdas/fetch-inject#29]
Allow an optional (possibly 2nd positional) argument of fetchInject, which would be a custom options object to pass directly to fetch. 

A use case where custom fetch options would be needed, would be trying to fetch a resource in  'no-cors' mode (i.e. the facebook sdk).

I would be happy to make a pull request with the above enhancement.

**Comment by TheT0dd** [comment]
My example use case is invalid, since 'no-cors' would result in an opaque response which in turn means the contents of the script could not be accessed and injected. 

I am closing the issue, unless there is another use case that benefits from custom fetch options.

**Comment by jhabdas** [comment]
I'm not opposed to allowing options, though I believe it can be configured outside the fetch request if I'm not mistaken. If you make any discoveries @TheT0dd please feel free to share them here or open another issue. Thanks for using Fetch Inject!
