### ISSUE TITLE
Question, not issue: Does fetch-inject prevent executing an injected library multiple times?

### ISSUE THREAD

**Issue by JSLibBundles** [jhabdas/fetch-inject#32]
Hello,
fetch-inject looks terrific, something I've been searching for for quite some time.  Question: Does it prevent the same library from being loaded _and executed_ multiple times?  

It seems most modern browsers won't load an identical library (based on URL?) more than once, but will load once and handle subsequent requests from cache.  Even so, the browser executes the library each time it is requested, even if it is loaded from cache.  I'm looking for something that will prevent additional executions for subsequent requests.

Will fetch-inject keep track of which libraries have executed and prevent multiple executions?
Thanks!

**Comment by ianwalter** [comment]
@JSLibBundles From reading the source, it doesn't seem to.

@jhabdas Would you accept a pull request for this? It could be introduced as an option if you want.

**Comment by jhabdas** [comment]
Hey guys sorry for the, ahem, months old response. There's no cache layer which would prevent a resource from loading multiple times at the moment. I considered caching with Web Storage in #11 but got sidetracked by other things. If you'd like to send up a pull request please feel free to send one in. but please understand I don't have much time to continue wrenching on this at the moment.

**Comment by jymbob** [comment]
For reference, I recently came up against this, hitting a race condition where two elements were both attempting to load an external JS library, using `(typeof window.foo == 'undefined')` to trigger the load. The second load appeared to break the bound eventlisteners on the first instance.
I worked around it by asking one element to wait and check again if the library wasn't loaded.

I'd love to see some form of tracking of previously executed fetches.

**Comment by jhabdas** [comment]
@jymbob fetch-inject takes an optional promise, which can be used to prevent script execution based on whatever the user desires. my suggestion would be to leverage this promise to check for an existing script. for those who're running across race conditions from scripts attempting to load/execute more than once my suggestion is to work on your app's build pipeline so it doesn't do that.

**Comment by jymbob** [comment]
Thanks. I'd missed that the promise was resolved _before_ injection. I'll rewrite with a promise which rejects if the script is already found.
