### ISSUE TITLE
Doesn't reject on 404

### ISSUE THREAD

**Issue by lukasoppermann** [jhabdas/fetch-inject#34]
Hey, this is a really neat package. 👍 

I am not sure if I found a bug or if I am doing something wrong. I have the following code:

```js
return fetchInject([
  `/js/notFound.js`
]).then((result) => {
    console.log(`We got it: `, result)
  }, (result) => {
    console.log(`Oh nooo, a 404: `, result)
  })
})
```

The console log is:

```
We got it:  
[…]
0: Object { text: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>Error</title>\n</head>\n<body>\n<pre>Cannot GET /js/notFound.js</pre>\n</body>\n</html>\n", blob: Blob }
length: 1
__proto__: Array []
```

The status code is a proper `404`. I would expect a 404 to result in a rejected promise. Is there a reason why it should not reject? Or did I mess something up?

Thanks for helping out.

**Comment by jhabdas** [comment]
Thanks for the issue @lukasoppermann and sorry for the slow reply.

`fetchInject` is a thin wrapper around `fetch` and uses `Promise.all` to determine when all resources have been fetched so it can execute things in order. According to [`Promise.all` dev docs](https://devdocs.io/javascript/global_objects/promise/all) if a promise rejects it should terminate asynchronously.

You can use `then` to grab the response text before the rejection occurs, which could come in handy if, for example, you wanted to display an error message to the user.

Sorry I can't be of more help right now. I'll leave this open for now in case someone else wants to try and provide additional help.

**Comment by jhabdas** [comment]
Yep, you got it. What you're seeing is actually a little bit of a feature allowing you to pry into the response synchronously before the entire chain rejects.

**Comment by jhabdas** [comment]
Also, thank you for you kind words ☝️I'm pleased to know some are getting use out of this library and working to improve web performance.
