### ISSUE TITLE
Download without execution.

### ISSUE THREAD

**Issue by lukasoppermann** [jhabdas/fetch-inject#35]
Hey,

Is it possible to just download and cache something without appending it to the Dom?

I would like to download a webfont but only show it if it is cached to avoid FOUT.

**Comment by jhabdas** [comment]
Sorry I was a little hasty in my reply before. Second (optional) param to the module's function signature is a `Promise`. It was added for recursive calls but can take any promise object. In other words, you can pass in a an unresolved promise and resolve it later. Just watch out for race conditions.
