### ISSUE TITLE
Untranspiled ES6 source code

### ISSUE THREAD

**Issue by dgdavid** [jhabdas/fetch-inject#36]
Hello @jhabdas 

FIrst of all, thanks for your work :)

Today I realized that my library is not working on Internet Explorer (11) due to the unstranspiled `fetch-inject` ES6 source code (among other small issues on my side that can be solved polyfilling).

I am also using [rollup](https://github.com/rollup/rollup) to build the final bundler, but making use of  [`rollup-plugin-babel`](https://github.com/rollup/rollup-plugin-babel) to transpile ES6/7. So, I solved this issue adding `node_modules/fetch-inject/dist/**` into the `include: []` option.

However, it would be great that `fetch-inject` will be distributed transpiled, as is recommended by `rollup-plugin-babel`

> We encourage library authors not to distribute code that uses untranspiled ES6 features

Thoughts?

---

<sub>Related to #33</sub>

**Comment by jhabdas** [comment]
Hi @dgdavid. Thanks for using Fetch Inject. I empathize with the best practice Rich and team noted in their docs and appreciate the suggestion but don't have the time to personally maintain a version with Babel integrated—I've been burned one too many times by breaking changes in the Babel framework.

Please feel free to fork and share a version using Babel with transpilation to ES5 for the community. I'm sure someone will thank you for it later. 😃

**Comment by dgdavid** [comment]
@jhabdas,

Thank you for share your rationale about you do not want to support a ES5 transpiled version. I completely understand your point of view.

However, maybe would be nice to add a tiny note about it in the README file, isn't it?

Regarding to do it myself, I really sorry, but I either cannot right now because, among other reasons, I am not focused in JavaScript right now and I have not time to maintain the proposed fork. I really hope that someone could do it if finally is truly necessary.

Again, thank you for both, the project itself and your time meeting issues.
