### ISSUE TITLE
Updated Documentation Around Request Object Creation

### ISSUE THREAD

**Issue by JamiesonRoberts** [jhabdas/fetch-inject#45]
Any complaints if I submit a PR with some updated documentation around the request objects. It not really explicitly clear that you can use that to modify the fetch request parameters (as per our discussion on the PR).

I think that it could be made a bit more explicit for quick consumption around the creation and passing in of a request object, give that all of the examples show only a basic URL, rather than a built out Request that matches the fetch API.

Thoughts @jhabdas?

**Comment by jhabdas** [comment]
@JamiesonRoberts going to close this as it's a little over 2 weeks old now. please feel free to pull against this later or simply drop in your notes here for posterity. thanks!
