### ISSUE TITLE
Best way to polyfill fetch?

### ISSUE THREAD

**Issue by ivancuric** [jhabdas/fetch-inject#6]
So, I've been using a similar-ish helper function so far:
```js
/**
 * Async script load
 * @param {URL} url
 */
export function injectScript(url) {
  return new Promise((resolve, reject) => {
    const js = document.createElement('script');
    js.src = url;
    js.defer = 'true';
    js.async = 'true';
    js.onload = resolve;
    js.onerror = reject;
    document.head.appendChild(js);
  });
}
```
I usually go about by putting all polyfills in a separate bundle and having an entry file like this:
```js
/* entry.js */
import { injectScript } from './utils';

const browserSupportsAllFeatures = window.Promise && window.fetch;
const loadApp = () => injectScript('/js/app.js');

if (browserSupportsAllFeatures)
  loadApp();
else {
  const js = document.createElement('script');
  js.src = '/js/polyfills.js';
  js.defer = 'true';
  js.onload = loadApp();
  document.body.appendChild(js);
}
```
Would a similar pattern be reccomended using this fetch-inject?

**Comment by jhabdas** [comment]
Looks good to me. I'm thinking you'd end up with something like this:

```js
import { fetchInject } from 'fetch-inject';

const browserSupportsAllFeatures = window.Promise && window.fetch;
const loadApp = () => fetchInject(['/js/app.js']);
const loadPolyfills = (cb) => /* ... */

browserSupportsAllFeatures
  ? loadApp()
  : loadPolyfills(loadApp)
```

Please let me know if you have any issues importing cleanly. I removed the `main` from the package manifest in hopes of spurring activity on [ES6 Module Interop](https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md) in Node. Would love to hear any feedback you have on your experience.

**Comment by ivancuric** [comment]
Will do. I just managed to understand the whole `(i,s,o,g,r,a,m)` mumbo-jumbo from injectors.js :D. I could basically use `script()` from there to load the polyfills Fetch-lessly.

PS:
Why aren't `window, document, 'script', resource.text, resolve()` hardcoded? It's not like they will change anytime, right?

**Comment by jhabdas** [comment]
> Why aren't `window, document, 'script', resource.text, resolve()` hardcoded? It's not like they will change anytime, right?

Mostly to decouple the injectors from the browser environment. I suspect doing so will make them easier to test in isolation with #4.

**Comment by jhabdas** [comment]
> Would setting async and defer on the scripts do anything useful?

[Nope](https://dev.w3.org/html5/spec-preview/the-script-element.html#attr-script-defer).

**Comment by jhabdas** [comment]
@ivancuric one sec, amending ☝️ . Linked to draft spec...

**Comment by jhabdas** [comment]
@ivancuric updated ☝️

**Comment by ivancuric** [comment]
Wasn't thinking about inlined scripts, but `src`-ed ones injected via `document.createElement('script')`. Of course that `async` and `defer` don't really make sense, since no network requests are being made by the tag.

**Comment by jhabdas** [comment]
> Of course that `async` and `defer` don't really make sense, since no network requests are being made by the tag.

Defer, not since it would defeat the purpose to wait until DOM was parsed IMO. But for `async`, if the UA were able to parse and execute them without blocking the run loop (which seems to be implied in the 5.2 spec, if only by error of omission), there would be a performance gain to scripts capable of being parsed and executed before DOM ready (those which do not touch to the DOM).

As for using `async` and/or `defer` with [DOM Script Element](https://www.stevesouders.com/blog/2009/04/27/loading-scripts-without-blocking/) approach, it's outside the scope of this library. However, I'd be very interested to know of any discoveries in this regard.

**Comment by ivancuric** [comment]
Just did some testing. Can't really find a performance difference between inlining scripts with `fetch-inject` and chain promising `createElement('script')` + `insertBefore`/`appendChild` ones.

What are the benefits of inlining?

**Comment by jhabdas** [comment]
> What are the benefits of inlining?

It really depends on your use case and needs. Please see out the README for use cases, background and contribution guidelines. Thanks!

**Comment by jhabdas** [comment]
@ivancuric could you try testing again using `v1.6.x`? I've added a feature to perform command queuing for injection. Please see README for updated syntax and use cases.

![bootstrap-4](https://cloud.githubusercontent.com/assets/440298/24649786/c474c626-195a-11e7-8af8-b0ba0bcc0a71.png)

**Comment by jhabdas** [comment]
Here's another example, and it doesn't matter what order the dependencies are downloaded. The promise recursion will ensure they are injected sequentially in order every time:

<img width="646" alt="screen shot 2017-04-04 at 5 36 07 pm" src="https://cloud.githubusercontent.com/assets/440298/24650610/4a7125d8-195d-11e7-9849-a9e071949c53.png">

And the related code snippet:

```js
(function () {
  if (!(window.fetch && window.Promise)) return
  /**
   * Fetch Inject v1.6.1
   * Copyright (c) 2017 Josh Habdas
   * @licence MIT
   */
  !function(e,t){"object"==typeof exports&&"undefined"!=typeof module?module.exports=t():"function"==typeof define&&define.amd?define(t):e.fetchInject=t()}(this,function(){"use strict";const e=function(e,t,n,o,r,i,c){i=t.createElement(n),c=t.getElementsByTagName(n)[0],i.type=o.blob.type,i.appendChild(t.createTextNode(o.text)),i.onload=r(o),c?c.parentNode.insertBefore(i,c):t.head.appendChild(i)},t=function(t,n){if(!t||!Array.isArray(t))return Promise.reject(new Error("`inputs` must be an array"));if(n&&!(n instanceof Promise))return Promise.reject(new Error("`promise` must be a promise"));const o=[],r=n?[].concat(n):[],i=[];return t.forEach(e=>r.push(window.fetch(e).then(e=>{return[e.clone().text(),e.blob()]}).then(e=>{return Promise.all(e).then(e=>{o.push({text:e[0],blob:e[1]})})}))),Promise.all(r).then(()=>{return o.forEach(t=>{i.push({then:n=>{"text/css"===t.blob.type?e(window,document,"style",t,n):e(window,document,"script",t,n)}})}),Promise.all(i)})};return t});
  fetchInject([
    '/assets/js/main.js'
  ], fetchInject([
    '/assets/js/vendor/superfish.min.js'
  ], fetchInject([
    '/assets/js/vendor/jquery.transit.min.js',
    '/assets/js/vendor/jquery.hoverIntent.js'
  ], fetchInject([
    '/assets/js/vendor/jquery.min.js'
  ]))))
})()
```

**Comment by jhabdas** [comment]
Also, regarding inlining versus Script Tag Injection, and the benefits of each, please refer to the following document (which would need to be updated to reflect current browser behavior): https://www.stevesouders.com/blog/2009/04/27/loading-scripts-without-blocking/

**Comment by jhabdas** [comment]
Closes by https://github.com/jhabdas/fetch-inject/commit/cb90766b2da62b21b4365c1c7f132fd3dee66bc7. No need to polyfill fetch to use this library.
